/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wb;

/**
 *
 * @author George
 */
public enum WB_PropertyType {
    //LOADED FROM properties.xml
    PROP_APP_TITLE,
    
    //APPLICATION ICONS
    //BASIC SCREEN CONTROL ICONS
    NEW_DRAFT_ICON,
    LOAD_DRAFT_ICON,
    SAVE_DRAFT_ICON,
    EXPORT_DRAFT_ICON,
    EXIT_ICON,
    
    //CONTROLS FOR CHANGING SCREENS
    TEAMS_SCREEN_ICON,
    PLAYERS_SCREEN_ICON,
    STANDINGS_SCREEN_ICON,
    DRAFT_SCREEN_ICON,
    MLBTEAMS_SCREEN_ICON,
    
    //DRAFT SCREEN CONTROL ICONS
    ADD_PLAYER_ICON,
    REMOVE_PLAYER_ICON,
    
    //TEAMS SCREEN CONTROL ICONS
    ADD_TEAM_ICON,
    REMOVE_TEAM_ICON,
    EDIT_TEAM_ICON,
    
    
    //DRAFT SCREEN CONTROL ICONS
    DRAFT_PLAYER_ICON,
    AUTO_DRAFT_ICON,
    PAUSE_DRAFT_ICON,
    
    //APPLICATION TOOLTIPS FOR BUTTONS
    NEW_DRAFT_TOOLTIP,
    LOAD_DRAFT_TOOLTIP,
    SAVE_DRAFT_TOOLTIP,
    DELETE_TOOLTIP,
    EXPORT_DRAFT_TOOLTIP,
    EXIT_TOOLTIP,
    TEAMS_SCREEN_TOOLTIP,
    PLAYERS_SCREEN_TOOLTIP,
    STANDINGS_SCREEN_TOOLTIP,
    DRAFT_SCREEN_TOOLTIP,
    MLBTEAMS_SCREEN_TOOLTIP,
    ADD_PLAYER_TOOLTIP,
    REMOVE_PLAYER_TOOLTIP,
    ADD_TEAM_TOOLTIP,
    REMOVE_TEAM_TOOLTIP,
    EDIT_TEAM_TOOLTIP,
    DRAFT_PLAYER_TOOLTIP,
    AUTODRAFT_TOOLTIP,
    PAUSE_DRAFT_TOOLTIP,
    
    WOLFIEBALL_TEMP_LABEL,
    
    //PLAYER POSITION LABELS
    PLAYER_AVAILABLE_LABEL,
    PLAYER_SEARCH_LABEL,
    
    
    //FANTASY TEAMS SCREEN LABELS
    FANTASY_TEAMS_LABEL,
    DRAFT_NAME_LABEL,
    SELECT_TEAM_LABEL,
    STARTING_LINEUP_LABEL,
    
    //FANTASY STANDINGS SCREEN LABELS
    FANTASY_STANDINGS_LABEL,
    
    //DRAFT SCREEN LABELS
    DRAFT_SUMMARY_LABEL,
    
    //MLB TEAMS SCREEN LABELS
    MLB_TEAMS_LABEL,
    PRO_TEAM_LABEL,
    
    //ERROR DIALOG MESSAGES
    POSITION_FULL_ERROR_MESSAGE,
    
    //VERIFICATION MESSAGES
    NEW_DRAFT_CREATED_MESSAGE,
    DRAFT_LOADED_MESSAGE,
    DRAFT_SAVED_MESSAGE,
    DRAFT_EXPORTED_MESSAGE,
    SAVE_UNSAVED_WORK_MESSAGE,
    REMOVE_ITEM_MESSAGE,
    
    
    
}
